// import { TextStyle } from 'react-native';

export type IFontType = {
  fontSize: number;
  fontWeight:
    | 'normal'
    | 'bold'
    | '100'
    | '200'
    | '300'
    | '400'
    | '500'
    | '600'
    | '700'
    | '800'
    | '900'
    | 100
    | 200
    | 300
    | 400
    | 500
    | 600
    | 700
    | 800
    | 900
    | 'ultralight'
    | 'thin'
    | 'light'
    | 'medium'
    | 'regular'
    | 'semibold'
    | 'condensedBold'
    | 'condensed'
    | 'heavy'
    | 'black'
    | undefined;
  lineHeight: number;
};
// 基础字体样式接口
interface IFontStyle {
  fontSize: number;
  fontWeight: string | number;
  lineHeight: number;
  fontFamily?: string;
}

export interface IEventItem {
  name: string;
  trigger: string;
  type: string;
  input: object;
  fieldMapping: object;
}

// 基础主题接口
interface IBasicTheme {
  // BP系列
  BP0: string;
  BP2: string;
  BP5: string;
  BP10: string;
  BP20: string;
  BP30: string;
  BP40: string;
  BP50: string;
  BP60: string;
  BP70: string;
  BP80: string;
  BP90: string;
  BP95: string;
  BP98: string;
  BP100: string;

  // BS系列
  BS0: string;
  BS2: string;
  BS5: string;
  BS10: string;
  BS20: string;
  BS30: string;
  BS40: string;
  BS50: string;
  BS60: string;
  BS70: string;
  BS80: string;
  BS90: string;
  BS95: string;
  BS98: string;
  BS100: string;

  // BT系列
  BT0: string;
  BT2: string;
  BT5: string;
  BT10: string;
  BT20: string;
  BT30: string;
  BT40: string;
  BT50: string;
  BT60: string;
  BT70: string;
  BT80: string;
  BT90: string;
  BT95: string;
  BT98: string;
  BT100: string;

  // S系列
  S0: string;
  S2: string;
  S5: string;
  S10: string;
  S20: string;
  S30: string;
  S40: string;
  S50: string;
  S60: string;
  S70: string;
  S80: string;
  S90: string;
  S95: string;
  S98: string;
  S100: string;

  // E系列
  E0: string;
  E2: string;
  E5: string;
  E10: string;
  E20: string;
  E30: string;
  E40: string;
  E50: string;
  E60: string;
  E70: string;
  E80: string;
  E90: string;
  E95: string;
  E98: string;
  E100: string;

  // W系列
  W0: string;
  W2: string;
  W5: string;
  W10: string;
  W20: string;
  W30: string;
  W40: string;
  W50: string;
  W60: string;
  W70: string;
  W80: string;
  W90: string;
  W95: string;
  W98: string;
  W100: string;

  // I系列
  I0: string;
  I2: string;
  I5: string;
  I10: string;
  I20: string;
  I30: string;
  I40: string;
  I50: string;
  I60: string;
  I70: string;
  I80: string;
  I90: string;
  I95: string;
  I98: string;
  I100: string;

  // N系列
  N0: string;
  N2: string;
  N5: string;
  N10: string;
  N20: string;
  N30: string;
  N40: string;
  N50: string;
  N60: string;
  N70: string;
  N80: string;
  N90: string;
  N95: string;
  N98: string;
  N100: string;

  // NS系列
  NS0: string;
  NS2: string;
  NS5: string;
  NS10: string;
  NS20: string;
  NS30: string;
  NS40: string;
  NS50: string;
  NS60: string;
  NS70: string;
  NS80: string;
  NS90: string;
  NS95: string;
  NS98: string;
  NS100: string;

  // C1系列
  C10: string;
  C12: string;
  C15: string;
  C110: string;
  C120: string;
  C130: string;
  C140: string;
  C150: string;
  C160: string;
  C170: string;
  C180: string;
  C190: string;
  C195: string;
  C198: string;
  C1100: string;

  // opacity系列
  opacity0: number;
  opacity1: number;
  opacity2: number;
  opacity3: number;
  opacity4: number;
  opacity5: number;
  opacity6: number;
  opacity7: number;
  opacity8: number;
  opacity9: number;
  opacity10: number;
  opacity11: number;
  opacity12: number;
  opacity13: number;
  opacity14: number;
  opacity15: number;
  opacity16: number;
  opacity17: number;
  opacity18: number;
  opacity19: number;
  opacity20: number;

  // radius系列
  radiusNone: number;
  radiusXs: number;
  radiusS: number;
  radiusM: number;
  radiusL: number;
  radiusXl: number;
  radiusXxl: number;
  radiusCircle: string;

  // spacing系列
  spacing0: number;
  spacing1: number;
  spacing2: number;
  spacing3: number;
  spacing4: number;
  spacing5: number;
  spacing6: number;
  spacing7: number;
  spacing8: number;
  spacing9: number;
  spacing10: number;
  spacing11: number;
  spacing12: number;
  spacing13: number;
  spacing14: number;
  spacing15: number;
  spacing16: number;
  spacing18: number;
  spacing31: number;

  // size系列
  size0: number;
  size1: number;
  size2: number;
  size3: number;
  size4: number;
  size5: number;
  size6: number;
  size7: number;
  size8: number;
  size9: number;
  size10: number;
  size11: number;
  size12: number;
  size13: number;
  size14: number;
  size15: number;
  size16: number;
  size17: number;
  size18: number;
  size19: number;
  size20: number;
  size21: number;
  size22: number;
  size23: number;
  size24: number;
  size25: number;
  size30: number;
  size40: number;
  size50: number;
  size60: number;
  size70: number;
  size80: number;
  size89: number;
  size90: number;
  size100: number;
  size110: number;

  // fontWeight系列
  fontWeight100: number;
  fontWeight200: number;
  fontWeight300: number;
  fontWeight400: number;
  fontWeight500: number;
  fontWeight600: number;
  fontWeight700: number;
  fontWeight800: number;
  fontWeight900: number;

  // fontSize系列
  fontSize10: number;
  fontSize12: number;
  fontSize14: number;
  fontSize16: number;
  fontSize18: number;
  fontSize20: number;
  fontSize24: number;
  fontSize28: number;
  fontSize32: number;
  fontSize36: number;
  fontSize44: number;
  fontSize56: number;
  fontSize64: number;
  fontSize72: number;

  // lineHeight系列
  lineHeightXs: number;
  lineHeightS: number;
  lineHeightM: number;
  lineHeightL: number;
  lineHeightXl: number;
  lineHeightXxl: number;
  lineHeightMax: number;

  // fontFamily系列
  fontFamilyEN: string;
  fontFamilyCN: string;
}

// 系统主题接口
interface ISystemTheme {
  // 文本相关
  textPrimary: string;
  textPrimaryDisabled: string;
  textSecondary: string;
  textTertiary: string;
  textFourth: string;
  textBpDefault: string;
  textBpHover: string;
  textBpPress: string;
  textBpDisabled: string;
  textBsDefault: string;
  textErrorDefault: string;
  textErrorHover: string;
  textErrorPress: string;
  textErrorDisabled: string;
  textInfoDefault: string;
  textInfoHover: string;
  textInfoPress: string;
  textInfoDisabled: string;
  textWarningDefault: string;
  textWarningHover: string;
  textWarningPress: string;
  textWarningDisabled: string;
  textSuccessDefault: string;
  textSuccessHover: string;
  textSuccessPress: string;
  textSuccessDisabled: string;
  textInverse: string;
  textInverseHover: string;
  textInversePress: string;
  textInverseDisabled: string;
  textLinkDefault: string;

  // 背景相关
  background: string;

  // 容器相关
  containerPrimary: string;
  containerPrimaryDisabled: string;
  containerSecondary: string;
  containerTertiary: string;
  containerFourth: string;
  containerBpDefault: string;
  containerBpHover: string;
  containerBpPress: string;
  containerBpDisabled: string;
  containerBsDefault: string;
  containerBsWeakDefault: string;
  containerBsWeakHover: string;
  containerBsWeakPress: string;
  containerBsWeakDisabled: string;
  containerBsWeakSecondary: string;
  containerBsWeakTertiary: string;
  containerErrorDefault: string;
  containerErrorHover: string;
  containerErrorPress: string;
  containerErrorDisabled: string;
  containerInfoDefault: string;
  containerInfoHover: string;
  containerInfoPress: string;
  containerInfoDisabled: string;
  containerWarningDefault: string;
  containerWarningHover: string;
  containerWarningPress: string;
  containerWarningDisabled: string;
  containerSuccessDefault: string;
  containerSuccessHover: string;
  containerSuccessPress: string;
  containerSuccessDisabled: string;
  containerErrorWeakDefault: string;
  containerErrorWeakHover: string;
  containerErrorWeakPress: string;
  containerErrorWeakDisabled: string;
  containerInverse: string;
  containerInverseHover: string;
  containerInversePress: string;
  containerInverseDisabled: string;
  containerOverlayWeak3: string;
  containerOverlayWeak: string;
  containerOverlayDefault: string;

  // 边框相关
  borderPrimaryDefault: string;
  borderPrimaryHover: string;
  borderPrimaryPress: string;
  borderPrimaryDisabled: string;
  borderBpDefault: string;
  borderBpHover: string;
  borderBpPress: string;
  borderBpDisabled: string;
  borderErrorDefault: string;
  borderErrorHover: string;
  borderErrorPress: string;
  borderErrorDisabled: string;
  borderInfoDefault: string;
  borderInfoHover: string;
  borderInfoPress: string;
  borderInfoDisabled: string;
  borderWarningDefault: string;
  borderWarningHover: string;
  borderWarningPress: string;
  borderWarningDisabled: string;
  borderSuccessDefault: string;
  borderSuccessHover: string;
  borderSuccessPress: string;
  borderSuccessDisabled: string;
  borderInverse: string;
  borderInverseHover: string;
  borderInversePress: string;
  borderInverseDisabled: string;

  // 分割线
  dividerDefault: string;
  dividerBp: string;

  // 圆角
  radiusCard: number;
  radiusInCard: number;
  radiusComp1: string;

  // 间距
  spaceMarginLeftRight: number;
  spaceMarginTop: number;
  spaceMarginBottom: number;
  spaceCardCardM: number;
  spaceCardCardL: number;
  spaceCardPaddingUpdownL: number;
  spaceCardPaddingLeftRightL: number;
  spaceCardPaddingUpdownS: number;
  spaceCardPaddingLeftRightS: number;
  spaceElementsMin: number;
  spaceElementsXxxs: number;
  spaceElementsXxs: number;
  spaceElementsXs: number;
  spaceElementsS: number;
  spaceElementsM: number;
  spaceElementsL: number;
  spaceElementsXl: number;
  spaceElementsXxl: number;
  spaceElements3Xl: number;

  // 图标尺寸
  sizeIconXs: number;
  sizeIconS: number;
  sizeIconM: number;
  sizeIconL: number;
  sizeIconXl: number;
  sizeIconXxl: number;

  // 组件尺寸
  sizeComphXxs: number;
  sizeComphXs: number;
  sizeComphS: number;
  sizeComphM: number;
  sizeComphL: number;
  sizeComphXl: number;
  sizeAiCardW: number;

  // 阴影
  shadowBase: string;
  shadowMap: string;
  shadowAiCard: string;
  shadowBook: string;

  // 英文字体样式
  enDisplayXl: IFontStyle;
  enDisplayL: IFontStyle;
  enDisplayM: IFontStyle;
  enDisplayS: IFontStyle;
  enDisplayXs: IFontStyle;
  enDisplayXxsStrong: IFontStyle;
  enDisplayXxs: IFontStyle;
  enHeadlineXlStrong: IFontStyle;
  enHeadlineLStrong: IFontStyle;
  enHeadlineMStrong: IFontStyle;
  enHeadlineSStrong: IFontStyle;
  enHeadlineXsStrong: IFontStyle;
  enHeadlineXxsStrong: IFontStyle;
  enBodyL: IFontStyle;
  enBodyM: IFontStyle;
  enBodyS: IFontStyle;
  enCaptionL: IFontStyle;
  enCaptionM: IFontStyle;
  enCaptionS: IFontStyle;

  // 中文字体样式
  cnDisplayXl: IFontStyle;
  cnDisplayL: IFontStyle;
  cnDisplayM: IFontStyle;
  cnDisplayS: IFontStyle;
  cnDisplayXs: IFontStyle;
  cnDisplayXxsStrong: IFontStyle;
  cnDisplayXxs: IFontStyle;
  cnHeadlineXlStrong: IFontStyle;
  cnHeadlineLStrong: IFontStyle;
  cnHeadlineMStrong: IFontStyle;
  cnHeadlineSStrong: IFontStyle;
  cnHeadlineXsStrong: IFontStyle;
  cnHeadlineXxsStrong: IFontStyle;
  cnBodyL: IFontStyle;
  cnBodyM: IFontStyle;
  cnBodyS: IFontStyle;
  cnCaptionL: IFontStyle;
  cnCaptionM: IFontStyle;
  cnCaptionS: IFontStyle;
}

// 组件主题接口
interface IComponentsTheme {
  // 组件相关的主题配置
}

// 完整主题接口
interface ITokenProps {
  basic: IBasicTheme;
  system: ISystemTheme;
  components: IComponentsTheme;
}
